accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.home, name="accounts-home"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/home.html"),
        name="logout",
    ),
    path("profile/<username>/", views.user_profile, name="userprofile"),
    path("user/profile/", views.clientuserProfileUpdate, name="user-profile"),
]

heckExample/urls.py
"""mysite URL Configuration

This will be our central URL file

Whenever the app server is launched all of the urls that are included below will have their path included

Make sur to add the path here of any new apps if we add them.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("accounts.urls")), #we want to be able to point to urls.py in our sub files
    path("", include("groceries.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groceries/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from PIL import Image
from django.db.models import Max


class User(AbstractUser):
    is_clientuser = models.BooleanField("clientuser status", default=True)
    phone = models.CharField(max_length=10, blank=True)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5, blank=True)
    latitude = models.CharField(max_length=20, blank=True)
    longitude = models.CharField(max_length=20, blank=True)
    about = models.CharField(max_length=1000, blank=True)




class UserRegisterData(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, related_name="uprofile"
    )
    user_profile_image = models.ImageField(
        default="default.png", upload_to="user_profile_pics", blank=True
    )

    def __str__(self):
        return f"{self.user.username} ClientUser Profile"

    def save(self, *args, **kwargs):
        super(UserRegisterData, self).save(*args, **kwargs)
        img = Image.open(self.user_profile_image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.user_profile_image.path)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserRegisterData, User

class ClientUserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["username"].label = "Username"
        self.fields["email"].label = "Email Address"
        self.fields["first_name"].label = "First Name"
        self.fields["last_name"].label = "Last Name"
        self.fields["about"].label = "Your Bio"

    l_choices = (("ny", "New York"), ("ca", "California"))
    ny_choices = (
        ("Manhattan", "Manhattan"),
        ("Brooklyn", "Brooklyn"),
        ("Queens", "Queens"),
        ("Staten Island", "Staten Island"),
        ("Bronx", "Bronx"),
    )

    email = forms.EmailField(required=True)

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    city = forms.ChoiceField(choices=ny_choices)
    state = forms.ChoiceField(choices=l_choices)
    zip_code = forms.CharField(required=True)
    about = forms.CharField(required=False)


    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "email",
            "first_name",
            "last_name",
            "address",
            "city",
            "state",
            "zip_code",
            "about",
        ]
        help_texts = {
            "username": ("Username can contain Letters, digits and @/./+/-/_ only.")
        }


class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = UserRegisterData
        fields = ["user_profile_image"]
        labels = {"user_profile_image": ("User Profile Picture")}


class ClientUserUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["about"].label = "Your Bio"
        self.fields["first_name"].label = "First Name"
        self.fields["last_name"].label = "Last Name"

    l_choices = (("ny", "New York"), ("ca", "California"))
    ny_choices = (
        ("Manhattan", "Manhattan"),
        ("Brooklyn", "Brooklyn"),
        ("Queens", "Queens"),
        ("Staten Island", "Staten Island"),
        ("Bronx", "Bronx"),
    )

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    city = forms.ChoiceField(choices=ny_choices)
    state = forms.ChoiceField(choices=l_choices)
    zip_code = forms.CharField(required=True)
    about = forms.CharField(required=False)

    class Meta:
        model = User
        fields = [
            "about",
            "first_name",
            "last_name",
            "address",
            "city",
            "state",
            "zip_code",
        ]
        help_texts = {
            "username": ("DONT UPDATE USERNAME")
        }

accounts/views.py
from django.urls import reverse
from django.contrib import messages
from .forms import (
    ClientUpdateForm,
    ClientUserRegistrationForm,
    ClientUserUpdateForm
)

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from .models import UserRegisterData, User, UserRegisterData
from django.template import loader






def home(request):
    context = {}
    return render(request, "accounts/home.html", context)



def register(request):
    if request.method == "POST":

        form = ClientUserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            user.is_active = True
            user_type = form.cleaned_data.get("user_type")
            if user_type == "Restaurant":
                user.is_restaurant = True
            elif user_type == "User":
                user.is_clientuser = True

            user.save()



            return redirect("/login")
    else:
        form = ClientUserRegistrationForm()
    return render(request, "accounts/register.html", {"form": form})


def user_profile(request, username):
    clientuser = User.objects.get(username=username)
    ruser = request.user
    context = {
        "user1": clientuser,
        "ruser": ruser,
    }

    template = loader.get_template("accounts/user_profile.html")

    return HttpResponse(template.render(context, request))


@login_required
def clientuserProfileUpdate(request):
    if request.method == "POST":
        clientUserUpdateForm = ClientUserUpdateForm(request.POST, instance=request.user)
        clientUpdateForm = ClientUpdateForm(
            request.POST, request.FILES, instance=request.user.uprofile
        )
        if clientUserUpdateForm.is_valid() and clientUpdateForm.is_valid():
            clientUserUpdateForm.save()
            clientUpdateForm.save()
            messages.success(request, "Account succesfully updated!")
            return redirect("/")
    else:
        clientUserUpdateForm = ClientUserUpdateForm(instance=request.user)
        clientUpdateForm = ClientUpdateForm(instance=request.user.uprofile)

    context = {
        "clientUserUpdateForm": clientUserUpdateForm,
        "clientUpdateForm": clientUpdateForm,
    }

    return render(request, "accounts/userUpdate.html", context)

accounts/templates/accounts/base.html
</head>
<body1>
    <header>
<a href="{% url 'accounts:accounts-home' %}">
            <h1 class="logo-text"><span>Test </span>Base Page</h1>
    </a>
        </div>


            <ul>
                <li><a href="/login" class="login">Login</a></li>
                <li><a href="/register" class="register">Register</a></li>

            </ul>

        <ul class="nav">
            {% if user.is_authenticated %}

                {% if user.is_clientuser %}

                    <li>
                        <a href="#">
                            <i class="fas fa-user"></i>
                            {{ user.username }}
                            <i class="fas fa-chevron-down" style="font-size: .8em;"></i>
                        </a>
                        <ul>
                            <li><a href="/user/profile">Edit My Profile</a></li>
                            <li><a href="/profile/{{user.username}}">Preview Profile</a></li>
                            <li><a href="/logout" class="logout">Logout</a></li>
                        </ul>
                    </li>
                {% endif %}
            {% else %}

                <a href="/login">
                           <i class="fas fa-user"></i>
                </a>

            </li>
                </ul>
            </li>
            {% endif %}
        </ul>
    </header>
</body1>

{% block body %}
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME PAGE TEST</title>
        <h1> HOME PAGE TEST</h1>
</head>
<body>

</body>
</html>


{% endblock %}

accounts/templates/accounts/login.html
{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block body %}


<!-- **FORMS** -->

{% if messages %}
  {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
          {{ message }}
      </div>
  {% endfor %}
{% endif %}


      <h2 class="ml-5">You have been successfully logged out!</h2>
      <div class="border-top pt-3">
          <small class="text-muted">
            <a class="ml-5" href="/login/shelter">Log In Again?</a>
          </small>
      </div>






{% endblock %}

accounts/templates/accounts/register.html
{% load crispy_forms_tags %}

<h1 class="form_title">Create Account</h1>

<form method= POST action="" class="signup">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">

        <button class="button" type="submit">Sign Up</button>
        <br>
        <br>
</form>

accounts/templates/accounts/userUpdate.html
{% extends 'accounts/base.html' %}

{% block body %}

{% load crispy_forms_tags %}

    <div class="content-section" style="max-width: 500px; margin-left: 50px;">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.uprofile.user_profile_image.url }}" style="width: 200px; height: 200px;
        margin-left: 20px;">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ clientUserUpdateForm|crispy }}
                {{ clientUpdateForm|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'accounts/base.html' %}

{% block body %}

<h1 class="mb-0 bread">{{user1.username}} Details</h1>



   <h3>About</h3>
      <p>{{user1.about}}</p>
   <h3>User City:</h3><p>{{user1.city}}</p>
   <h3>User State: </h3><p>{{user1.state}}</p>
   <h3>Contact email: </h3><p>{{user1.email}}</p>
 </div>

{% endblock %}